name: Commit SHA Notifier

on:
  push:
    branches:
      - main

jobs:
  notify-commit-sha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests twilio

    - name: Notify Latest Commit SHA via WhatsApp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
        YOUR_WHATSAPP_NUMBER: ${{ secrets.YOUR_WHATSAPP_NUMBER }}
      run: |
        import requests
        from twilio.rest import Client

        def get_latest_commit_sha():
            response = requests.get(f"https://api.github.com/repos/${{ github.repository }}/commits?per_page=1", headers={"Authorization": f"token ${{ secrets.GITHUB_TOKEN }}"})
            commits = response.json()
            return commits[0]['sha']

        def send_whatsapp_message(commit_sha):
            client = Client("${{ secrets.TWILIO_ACCOUNT_SID }}", "${{ secrets.TWILIO_AUTH_TOKEN }}")
            message = client.messages.create(
                                    body=f"Latest Commit SHA: {commit_sha}",
                                    from_='whatsapp:${{ secrets.TWILIO_WHATSAPP_NUMBER }}',
                                    to='whatsapp:${{ secrets.YOUR_WHATSAPP_NUMBER }}'
                                )
            print(message.sid)

        latest_commit_sha = get_latest_commit_sha()
        send_whatsapp_message(latest_commit_sha)
